# Generated by Django 5.2.4 on 2025-07-20 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('short_description', models.CharField(max_length=300)),
                ('detailed_description', models.TextField()),
                ('image', models.ImageField(upload_to='projects/')),
                ('client_name', models.CharField(blank=True, max_length=100)),
                ('project_url', models.URLField(blank=True)),
                ('technologies_used', models.CharField(max_length=200)),
                ('date_completed', models.DateField()),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
