# Generated by Django 5.2.4 on 2025-08-05 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_service_icon_service_image'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='multi_images/')),
                ('aspect', models.CharField(choices=[('banner', 'Banner'), ('gallery', 'Gallery'), ('thumbnail', 'Thumbnail'), ('process', 'Process Step'), ('other', 'Other')], default='gallery', max_length=50)),
                ('alt_text', models.CharField(blank=True, help_text='SEO-friendly alt text', max_length=150)),
                ('order', models.PositiveIntegerField(default=0, help_text='Image display order')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
