# Generated by Django 5.2.4 on 2025-08-05 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_multiimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multiimage',
            name='aspect',
        ),
        migrations.RemoveField(
            model_name='multiimage',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='multiimage',
            name='object_id',
        ),
        migrations.AddField(
            model_name='multiimage',
            name='blog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='multi_images', to='app.blog'),
        ),
        migrations.AddField(
            model_name='multiimage',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='multi_images', to='app.project'),
        ),
        migrations.AddField(
            model_name='multiimage',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='multi_images', to='app.service'),
        ),
    ]
